### ISSUE TITLE
Migrate scripts from using os.path to using Pathlib

### ISSUE THREAD

**Issue by tim-fry** [openmc-dev/data#17]
This issue is added in response to a requirement from @Shimwell and @ukaea.

In the scripts there is an extensive use of os.path library for finding files and directories. In some scripts the code has started using PathLib instead of os.path. 

I'm planning to update all of the current scripts to replace uses of os.path with the newer object orientated PathLib (https://docs.python.org/3/library/pathlib.html) library. I'll make sure that the use of PathLib is kept consistent with those scripts in which it's already used.

**Comment by paulromano** [comment]
@tim-fry Yes, I'm all for using pathlib over os.path. I'm actually already working on refactoring the scripts in the `scripts/` directory based on feedback from the review in #1455 and started using pathlib there.

**Comment by paulromano** [comment]
Ah sorry, I'm talking about the wrong repo here -- I've been refactoring scripts in openmc-dev/openmc, not here. Feel free to take a stab at the ones here!

**Comment by Shimwell** [comment]
Yes please @tim-fry this would be a nice addition. I guess this is being worked on by yourself and might overlap with some of the work others in your group are doing @SamPUG
