### ISSUE TITLE
No BWR burnup chain for depletion analysis in BWR

### ISSUE THREAD

**Issue by fuadnse03** [openmc-dev/data#32]
I am trying to do depletion analysis in a BWR assembly but I have noticed that there is no depletion chain for BWR spectrum for any data library.Is there any possibility of getting the depletion chain of BWR asap?
Thanks in advance

**Comment by paulromano** [comment]
The only thing that the spectrum actually affects in the depletion chain is the capture branching ratio for a handful of reactions. A BWR will still have a thermal spectrum like a PWR so I wouldn't expect those branching ratios to be appreciably different.
