### ISSUE TITLE
Quick questions regarding GND and the future of OpenMC data

### ISSUE THREAD

**Issue by cjwyett** [openmc-dev/data#37]
Hi, 

Apologies for putting this here, I know it's not a discussion board.

You guys are using GND naming convention, I'm guessing this is in anticipation of working more closely with GND in the future? 

If this is the case, what GND features could be the most advantageous to OpenMC? What will you need to work on to implement GND? 

Cheers

**Comment by Shimwell** [comment]
I guess we have incident neutron class with from_ace, from_endf from_hdf5 options so presumably we would need a from_gnd class. It looks much easier to parse than ace and endf so that is nice.

**Comment by paulromano** [comment]
Hi @cjwyett. OpenMC uses its own HDF5 format that is hierarchical in structure like GND. Much of my original hope was that OpenMC might be able to use GND directly. I'm not so sure at this point that will be the endpoint. However, as @Shimwell implied, being able to start from GND data and produce HDF5 data would be a good start through a `from_gnd` method. My sense is that the ecosystem hasn't really moved off of the ENDF-6 format yet. Once we get to a point where evaluators want to use the GND format to store data that can't be handled in ENDF-6, we'd probably see more of a shift toward GND and away from ENDF.

Anyway, let us know your thoughts, especially if you are actively involved in GND efforts.

**Comment by cjwyett** [comment]
Thanks for your replies and interesting observations. 

> Anyway, let us know your thoughts, especially if you are actively involved in GND efforts

I'm not involved in any nuclear data projects so unfortunately have no interesting thoughts of my own. It will be of course be a great relief to get away from those disgusting ENDF files. `from_gnd` sounds like a dream, I look forward to the day.

**Comment by paulromano** [comment]
Yes, hopefully one day we'll get there. @cjwyett If you have more questions, I'd encourage you to join the OpenMC [user's group](https://groups.google.com/forum/#!forum/openmc-users).
