### ISSUE TITLE
Invalid literal for int() with base 10: 'E+'

### ISSUE THREAD

**Issue by AI-Pranto** [openmc-dev/data#44]
Neutron sub-library files = nndc-7.1
Decay sub-library files = [decay](http://atom.kaeri.re.kr/NDVG/showdata.jsp?file=origen.rev03.decay&ty=E71&form=Dec_ENDF&num=a_E71&st=merged)
Fission-Yields = [nfy](http://atom.kaeri.re.kr/NDVG/scale_Lib.jsp?select=YLDE71)

And I ended up with the following error.....
```
Processing decay sub-library files...
------------------------------------------------------------------------
~/anaconda3/envs/openmc12/lib/python3.8/site-packages/openmc/deplete/chain.py in from_endf(cls, decay_files, fpy_files, neutron_files, progress)
    298         decay_data = {}
    299         for f in decay_files:
--> 300             data = openmc.data.Decay(f)
    301             # Skip decay data for neutron itself
    302             if data.nuclide['atomic_number'] == 0:

~/anaconda3/envs/openmc12/lib/python3.8/site-packages/openmc/data/decay.py in __init__(self, ev_or_filename)
    315             ev = ev_or_filename
    316         else:
--> 317             ev = Evaluation(ev_or_filename)
    318 
    319         file_obj = StringIO(ev.section[8, 457])

~/anaconda3/envs/openmc12/lib/python3.8/site-packages/openmc/data/endf.py in __init__(self, filename_or_obj)
    413             position = fh.tell()
    414             line = fh.readline()
--> 415             MF = int(line[70:72])
    416         self.material = int(line[66:70])
    417         fh.seek(position)

ValueError: invalid literal for int() with base 10: 'E+'
```

In that case, we can fix this problem by simply calling float first `int(float(input))`. But not a global solution. Thoughts?

**Comment by paulromano** [comment]
The files that you are using entering for decay and fission product yields are not ENDF files, which is why it fails to read them. The `Chain.from_endf` method takes only ENDF files. For example, you can find the decay and fission product yield sublibraries for ENDF/B-VIII.0 [here](https://www.nndc.bnl.gov/endf/b8.0/download.html).
