### ISSUE TITLE
No such file or directory: 'njoy'

### ISSUE THREAD

**Issue by Bugami** [openmc-dev/data#55]
I have an issue to generate cross section library from generate_endf.py

when I ran the code, it was everything is good for downloading and extracting the files for neutron, proton and thermal scattering

when it start to convert, it shows me the error such as /home/abugami/anaconda3/envs/openmc-env/xs/data/endfb-viii.0-endf/neutron/n-092_U_238.endf /home/abugami/anaconda3/envs/openmc-env/xs/data/endfb-viii.0-endf/neutron/tsl-UinUO2.endf [Errno 2] No such file or directory: 'njoy'

**Comment by Shimwell** [comment]
Yes for some of these scripts the NJOY software package is needed. 

We tend to install it like this https://github.com/openmc-dev/openmc/blob/b62708f911d05e269e5c3083287e70d050ed35f9/Dockerfile#L38

**Comment by Bugami** [comment]
I am using anaconda3. how to install NJOY software package on it?

**Comment by paulromano** [comment]
@Bugami with your conda environment activated, you should follow the [installation instructions from NJOY itself](https://docs.njoy21.io/install.html). Once it is installed, you should have an `njoy` executable available that OpenMC can use.
